# -*- coding: utf-8 -*-
"""AutoPilot to OpenAI.ipynb

Automatically generated by Colaboratory.

"""

#!pip install openai

import openai

openai.api_key = OPENAI_KEY

sys_msg = "Respond in a numbered list of simple and succinct instructions of how to complete the given task. The instructions should be basic computer inputs such as moving the mouse or hitting keys on the keyboard. Do not provide any unnecessary information such as alternative ways to complete the task, just provide each instruction precisely and succintly with each instruction as its own bullet point."

completion = openai.ChatCompletion.create(
  model="gpt-4",
  messages=[
    {"role": "system", "content": sys_msg},
    {"role": "user", "content": "What are the steps to create a new folder in Documents titled 'cream'?"}
  ]
)

res = completion.choices[0].message

print("Received response:")
print(res)

l = res["content"].split("\n")

print(l)

